"""Unprivileged systemd deployment planning: script rendering and status.

Deployment effects are returned as reviewable POSIX-sh scripts: breezed spawns
no sudo/pkexec; the user escalates by running the script themselves
(``sudo sh <path>``). ``daemon_status`` is the only execution path and stays
unprivileged.
"""

import datetime as dt
import os
import re
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Protocol

from breezed import __version__
from breezed.types import DomainError

SERVICE_NAME = "breezed"
EXEC_PATH = "/usr/local/bin/breezed"
ENV_MODE = 0o640

_UNIT_STAMP_RE = re.compile(r"^# Installed by breezed (\S+) on ", re.MULTILINE)

_ENV_SKELETON = """\
# breezed environment file — holds the iDRAC secrets.
# The installer never overwrites this file; edit values in place.
IDRAC_HOST=
IDRAC_USER=
IDRAC_PASSWORD=
"""

_INSTALL_SCRIPT_TEMPLATE = """\
#!/bin/sh
# breezed install script — generated by `breezed daemon install`.
# POSIX sh + GNU coreutils. Self-contained and idempotent: safe to review,
# re-run for upgrades, and audit.
# BREEZED_INSTALL_ROOT: when set, every target path is prefixed with it
# (testing only — production runs leave it unset, so targets live under /).
set -eu

__PROLOGUE__
CONFIG_OWNER="${BREEZED_CONFIG_OWNER:-${SUDO_USER:-root}}"

echo "[breezed-install] copying runtime to $ROOT/opt/breezed"
rm -rf "$ROOT/opt/breezed.old"
if [ -d "$ROOT/opt/breezed" ]; then
    mv "$ROOT/opt/breezed" "$ROOT/opt/breezed.old"
fi
mkdir -p "$ROOT/opt"
cp -a "$SRC_VENV" "$ROOT/opt/breezed"

mkdir -p "$ROOT/usr/local/bin"
ln -sfn "$ROOT/opt/breezed/bin/breezed" "$ROOT/usr/local/bin/breezed"

echo "[breezed-install] relocating bundled interpreter out of the source prefix"
BASE_BIN="$(sed -n "s/^home = //p" "$ROOT/opt/breezed/pyvenv.cfg")"
BASE_DIR="$(dirname "$BASE_BIN")"
rm -rf "$ROOT/opt/breezed-python.old"
if [ -d "$ROOT/opt/breezed-python" ]; then
    mv "$ROOT/opt/breezed-python" "$ROOT/opt/breezed-python.old"
fi
cp -a "$BASE_DIR" "$ROOT/opt/breezed-python"
sed -i "s|^home = .*|home = ${ROOT}/opt/breezed-python/bin|" "$ROOT/opt/breezed/pyvenv.cfg"
for py in "$ROOT"/opt/breezed/bin/python*; do
    if [ -L "$py" ]; then
        target="$(readlink -f "$py")"
        rm -f "$py"
        cp -a "$target" "$py"
    fi
done

for shim in "$ROOT"/opt/breezed/bin/*; do
    if [ ! -L "$shim" ]; then
        case "${shim##*/}" in
            activate|activate.*) ;;
            *)
                if [ "$(head -c 2 "$shim" 2>/dev/null)" = "#!" ]; then
                    sed -i "1s|.*|#!${ROOT}/opt/breezed/bin/python3|" "$shim"
                    echo "[breezed-install] relocated shebang: $shim"
                fi
                ;;
        esac
    fi
done

echo "[breezed-install] writing $ROOT/etc/systemd/system/breezed.service"
mkdir -p "$ROOT/etc/systemd/system"
cat > "$ROOT/etc/systemd/system/breezed.service" <<'BREEZED_UNIT_EOF'
__UNIT__
BREEZED_UNIT_EOF

FRESH_ENV=0
if [ -f "$ROOT/etc/breezed.env" ]; then
    echo "[breezed-install] keeping existing $ROOT/etc/breezed.env"
else
    cat > "$ROOT/etc/breezed.env" <<'BREEZED_ENV_EOF'
__ENV__
BREEZED_ENV_EOF
    echo "[breezed-install] wrote env skeleton $ROOT/etc/breezed.env"
    FRESH_ENV=1
fi
chmod __ENV_MODE__ "$ROOT/etc/breezed.env"
if ! chown root:breezed "$ROOT/etc/breezed.env" 2>/dev/null; then
    echo "[breezed-install] warning: could not enforce root:breezed on $ROOT/etc/breezed.env" >&2
fi

mkdir -p "$ROOT/etc/breezed"
if [ -f "$ROOT/etc/breezed/breezed.toml" ]; then
    echo "[breezed-install] keeping existing $ROOT/etc/breezed/breezed.toml"
else
    cat > "$ROOT/etc/breezed/breezed.toml" <<'BREEZED_CONFIG_EOF'
__CONFIG__
BREEZED_CONFIG_EOF
    echo "[breezed-install] installed example config $ROOT/etc/breezed/breezed.toml"
fi
if chown "$CONFIG_OWNER" "$ROOT/etc/breezed/breezed.toml" 2>/dev/null; then
    chmod 0664 "$ROOT/etc/breezed/breezed.toml"
    echo "[breezed-install] config owner: $CONFIG_OWNER (0664)"
else
    echo "[breezed-install] warning: could not chown $CONFIG_OWNER on breezed.toml;" \\
        "leaving permissions untouched" >&2
fi

if id breezed >/dev/null 2>&1; then
    echo "[breezed-install] system user breezed already present"
else
    useradd --system --no-create-home --shell /usr/sbin/nologin breezed
    echo "[breezed-install] created system user breezed"
fi

echo "[breezed-install] smoke test $ROOT/opt/breezed/bin/breezed --version"
if ! "$ROOT/opt/breezed/bin/breezed" --version >/dev/null 2>&1; then
    echo "[breezed-install] ERROR: standalone binary failed to run" >&2
    if [ -d "$ROOT/opt/breezed.old" ]; then
        echo "[breezed-install] restore hint: rm -rf $ROOT/opt/breezed && \\
mv $ROOT/opt/breezed.old $ROOT/opt/breezed" >&2
    fi
    exit 1
fi
echo "[breezed-install] smoke test passed"

START_REQUESTED=0
if [ -z "$ROOT" ]; then
    systemctl daemon-reload
__START_BLOCK__
fi

if [ "$FRESH_ENV" -eq 1 ]; then
    if [ "$START_REQUESTED" -eq 1 ]; then
        echo "[breezed-install] NOTE: the unit will fail until secrets are set"
    fi
    echo "[breezed-install] secrets are EMPTY — fill them:"
    echo "[breezed-install]   sudoedit $ROOT/etc/breezed.env"
    echo "[breezed-install]     (IDRAC_HOST/IDRAC_USER/IDRAC_PASSWORD)"
    echo "[breezed-install]   sudo systemctl restart breezed"
else
    echo "[breezed-install] runtime updated — restart to pick it up:"
    echo "[breezed-install]   sudo systemctl restart breezed"
fi

echo "[breezed-install] done — systemctl status breezed"
"""

_START_BLOCK = "    systemctl enable --now breezed\n    START_REQUESTED=1"

_NO_START_BLOCK = "    # start not requested; unit left disabled"

_UNINSTALL_SCRIPT_TEMPLATE = """\
#!/bin/sh
# breezed uninstall script — generated by `breezed daemon uninstall`.
# Disables and removes the unit and the /usr/local/bin/breezed shim; keeps the
# system user, /etc/breezed.env, and /etc/breezed/.
# BREEZED_INSTALL_ROOT: when set, every target path is prefixed with it
# (testing only — production runs leave it unset, so targets live under /).
set -eu

__PROLOGUE__

if [ -z "$ROOT" ]; then
    if systemctl disable --now breezed >/dev/null 2>&1; then
        echo "[breezed-uninstall] disabled and stopped breezed"
    else
        echo "[breezed-uninstall] unit was not enabled or active (continuing)"
    fi
    systemctl daemon-reload
fi

rm -f "$ROOT/etc/systemd/system/breezed.service"
rm -f "$ROOT/usr/local/bin/breezed"

echo "[breezed-uninstall] kept system user, /etc/breezed.env, and /etc/breezed/"
echo "[breezed-uninstall] done"
"""


class DaemonError(DomainError):
    """Deployment failures with actionable messages; never raw OSError text."""


def _PROLOGUE(tag: str) -> str:
    """Shared prologue: sandbox-root extraction plus the unprivileged root check."""
    return (
        'if [ -n "${BREEZED_INSTALL_ROOT:-}" ]; then\n'
        '    ROOT="${BREEZED_INSTALL_ROOT%/}"\n'
        "else\n"
        '    ROOT=""\n'
        "fi\n"
        "\n"
        'if [ -z "$ROOT" ] && [ "$(id -u)" -ne 0 ]; then\n'
        f'    echo "[{tag}] ERROR: root privileges are required" >&2\n'
        f'    echo "[{tag}] re-run exactly: sudo sh $0" >&2\n'
        "    exit 1\n"
        "fi\n"
    )


def _PROLOGUE_SRC_VENV(tag: str, src_venv: str) -> str:
    return (
        _PROLOGUE(tag)
        + "\n"
        + f'SRC_VENV="{src_venv}"\n'
        + 'if ! cd "$SRC_VENV" >/dev/null 2>&1; then\n'
        + f'    echo "[{tag}] ERROR: source runtime not found: $SRC_VENV" >&2\n'
        + "    exit 1\n"
        + "fi\n"
        + 'SRC_VENV="$(pwd -P)"\n'
        + 'for deployed in "$ROOT/opt/breezed" "$ROOT/opt/breezed-python"; do\n'
        + '    if [ "$(cd "$deployed" 2>/dev/null && pwd -P)" = "$SRC_VENV" ]; then\n'
        + f'        echo "[{tag}] ERROR: refusing to copy the deployed runtime onto itself" >&2\n'
        + '        echo "[breezed-install] generate scripts from a dev install '
        '(~/.local/bin/breezed)" >&2\n' + "        exit 1\n" + "    fi\n" + "done\n"
    )


@dataclass(frozen=True, slots=True)
class InstallerPaths:
    unit_path: Path = Path("/etc/systemd/system/breezed.service")
    env_path: Path = Path("/etc/breezed.env")
    config_dir: Path = Path("/etc/breezed")


class FileOps(Protocol):
    """Read-only FS seam used by status(); fakes replace it in tests."""

    def read_text(self, path: Path) -> str: ...
    def stat(self, path: Path) -> os.stat_result | None: ...  # None when absent


class RealFileOps:
    """The one production FileOps; thin delegation onto pathlib/os."""

    def read_text(self, path: Path) -> str:
        return path.read_text()

    def stat(self, path: Path) -> os.stat_result | None:
        if not path.exists():
            return None
        return path.stat()


CommandRunner = Callable[[list[str]], str]
"""Runs systemctl invocations for probes; returns stdout, raises DaemonError on failure."""


def _run_systemctl(argv: list[str]) -> str:
    """Default CommandRunner: thin wrapper around subprocess.run (sanctioned site).

    Executes ``argv`` verbatim and returns stdout; raises ``DaemonError`` on a
    non-zero exit (expected for probes — callers that query catch it), missing
    binary, or timeout.
    """
    try:
        completed = subprocess.run(argv, capture_output=True, text=True, check=False, timeout=30)
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"{' '.join(argv)} failed to run: {exc}"
        raise DaemonError(msg) from exc
    if completed.returncode != 0:
        snippet = _first_line(completed.stderr)
        msg = f"{' '.join(argv)} failed (rc={completed.returncode}): {snippet}"
        raise DaemonError(msg)
    return completed.stdout


def _first_line(text: str) -> str:
    stripped = text.strip().splitlines()
    return stripped[0][:200] if stripped else ""


def _read_packaged(name: str) -> str:
    candidate = resources.files("breezed").joinpath("templates").joinpath(name)
    if not candidate.is_file():
        msg = f"packaged resource missing: {name}"
        raise DaemonError(msg)
    return candidate.read_text(encoding="utf-8")


@dataclass(frozen=True, slots=True)
class DaemonStatus:
    unit_present: bool
    active: bool
    enabled: bool
    unit_version: str | None
    binary_version: str


def _render_unit() -> str:
    template = _read_packaged("breezed.service.template")
    installed_at = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    return (
        template.replace("{version}", __version__)
        .replace("{installed_at}", installed_at)
        .replace("{exec_path}", EXEC_PATH)
    )


def _probe_flag(runner: CommandRunner, argv: list[str], ok_values: set[str]) -> bool:
    try:
        output = runner(argv)
    except DaemonError:
        return False
    return output.strip() in ok_values


_default_paths: InstallerPaths = InstallerPaths()
_default_fs: FileOps = RealFileOps()


def daemon_status(
    paths: InstallerPaths = _default_paths,
    *,
    runner: CommandRunner = _run_systemctl,
    fs: FileOps = _default_fs,
) -> DaemonStatus:
    unit_present = fs.stat(paths.unit_path) is not None
    unit_version: str | None = None
    if unit_present:
        try:
            unit_text = fs.read_text(paths.unit_path)
        except OSError:
            unit_text = ""
        match = _UNIT_STAMP_RE.search(unit_text)
        if match is not None:
            unit_version = match.group(1)
    return DaemonStatus(
        unit_present=unit_present,
        active=_probe_flag(runner, ["systemctl", "is-active", SERVICE_NAME], {"active"}),
        enabled=_probe_flag(
            runner, ["systemctl", "is-enabled", SERVICE_NAME], {"enabled", "enabled-runtime"}
        ),
        unit_version=unit_version,
        binary_version=__version__,
    )


def _ensure_not_deployed_runtime(install_root: str) -> None:
    """Refuse generation when this process runs from inside the deploy target.

    The live incident: /usr/local/bin/breezed shadowed ~/.local/bin, so the
    generator ran from /opt/breezed and embedded it as SRC_VENV — copying
    the deployed runtime onto itself.
    """
    stripped = install_root.rstrip("/")
    prefix = Path(sys.prefix).resolve()
    for name in ("opt/breezed", "opt/breezed-python"):
        target = Path(f"{stripped}/{name}").resolve()
        if prefix == target or target in prefix.parents:
            msg = (
                f"this is the deployed runtime ({target}); generate install "
                "scripts from a development install instead (e.g. ~/.local/bin/breezed)"
            )
            raise DaemonError(msg)


def render_install_script(*, start: bool) -> str:
    """Return a self-contained POSIX-sh install script; no side effects."""
    install_root = os.environ.get("BREEZED_INSTALL_ROOT", "")
    _ensure_not_deployed_runtime(install_root)
    for label, value in (("sys.prefix", sys.prefix), ("BREEZED_INSTALL_ROOT", install_root)):
        if any(ch in value for ch in ("'", '"', "$", "\n")):
            msg = f"{label} is not safe to embed in a shell script: {value!r}"
            raise DaemonError(msg)
    substitutions = {
        "__PROLOGUE__": _PROLOGUE_SRC_VENV("breezed-install", sys.prefix),
        "__UNIT__": _render_unit(),
        "__ENV__": _ENV_SKELETON,
        "__CONFIG__": _read_packaged("breezed.toml.example"),
        "__ENV_MODE__": f"{ENV_MODE:o}",
        "__START_BLOCK__": _START_BLOCK if start else _NO_START_BLOCK,
    }
    script = re.sub(
        r"__[A-Z_]+__",
        lambda match: substitutions[match.group(0)],
        _INSTALL_SCRIPT_TEMPLATE,
    )
    leftover = re.search(r"__[A-Z_]+__", script)
    if leftover is not None:
        msg = f"install script render left unsubstituted placeholder {leftover.group(0)}"
        raise DaemonError(msg)
    return script.rstrip("\n") + "\n"


def render_uninstall_script() -> str:
    """Return a self-contained POSIX-sh uninstall script; no side effects."""
    install_root = os.environ.get("BREEZED_INSTALL_ROOT", "")
    _ensure_not_deployed_runtime(install_root)
    return _UNINSTALL_SCRIPT_TEMPLATE.replace("__PROLOGUE__", _PROLOGUE("breezed-uninstall"))


__all__ = [
    "EXEC_PATH",
    "CommandRunner",
    "DaemonError",
    "DaemonStatus",
    "FileOps",
    "InstallerPaths",
    "RealFileOps",
    "SERVICE_NAME",
    "daemon_status",
    "render_install_script",
    "render_uninstall_script",
]
