"""Idempotent systemd deployment: script rendering and status of the unit.

Deployment effects are returned as reviewable POSIX-sh scripts; nothing here
executes privileged operations. ``daemon_status`` is the only execution path
and stays unprivileged. Every filesystem read goes through the injected
``FileOps`` seam; every process invocation through the injected
``CommandRunner``.
"""

import datetime as dt
import os
import re
import subprocess
from collections.abc import Callable
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Protocol

from breezed import __version__
from breezed.types import DomainError

SERVICE_NAME = "breezed"
EXEC_PATH = "/usr/local/bin/breezed"
ENV_MODE = 0o640

_UNIT_STAMP_RE = re.compile(r"^# Installed by breezed (\S+) on ", re.MULTILINE)

_ENV_SKELETON = """\
# breezed environment file — holds the iDRAC secrets.
# The installer never overwrites this file; edit values in place.
IDRAC_HOST=
IDRAC_USER=
IDRAC_PASSWORD=
"""

_INSTALL_SCRIPT_TEMPLATE = """\
#!/bin/sh
# breezed install script — generated by `breezed daemon install`.
# Idempotent: safe to re-run for upgrades. Never overwrites an existing env file
# or config.
set -eu

if [ "$(id -u)" -ne 0 ]; then
    echo "breezed-install: root privileges are required" >&2
    echo "breezed-install: re-run exactly: sudo sh $0" >&2
    exit 1
fi

cat > /etc/systemd/system/breezed.service <<'UNIT_EOF'
__UNIT__
UNIT_EOF

if [ ! -f /etc/breezed.env ]; then
    cat > /etc/breezed.env <<'ENV_EOF'
__ENV__
ENV_EOF
fi
chmod __ENV_MODE__ /etc/breezed.env

mkdir -p /etc/breezed
if [ ! -f /etc/breezed/breezed.toml ]; then
    cat > /etc/breezed/breezed.toml <<'CONFIG_EOF'
__CONFIG__
CONFIG_EOF
fi

systemctl daemon-reload
__START_BLOCK__
"""

_START_BLOCK = """systemctl enable --now SERVICE_NAME"""
_NO_START_BLOCK = ":  # not started (--start not given); run: sudo systemctl enable --now breezed"

_UNINSTALL_SCRIPT_TEMPLATE = """\
#!/bin/sh
# breezed uninstall script — generated by `breezed daemon uninstall`.
# Disables and removes the unit; keeps the user, env file, and config.
set -eu

if [ "$(id -u)" -ne 0 ]; then
    echo "breezed-uninstall: root privileges are required" >&2
    echo "breezed-uninstall: re-run exactly: sudo sh $0" >&2
    exit 1
fi

systemctl disable --now SERVICE_NAME || true
rm -f /etc/systemd/system/breezed.service
systemctl daemon-reload
"""


class DaemonError(DomainError):
    """Deployment failures with actionable messages; never raw OSError text."""


@dataclass(frozen=True, slots=True)
class InstallerPaths:
    unit_path: Path = Path("/etc/systemd/system/breezed.service")
    env_path: Path = Path("/etc/breezed.env")
    config_dir: Path = Path("/etc/breezed")


class FileOps(Protocol):
    """Read-only FS seam — writes happen inside the escalated script."""

    def read_text(self, path: Path) -> str: ...
    def stat(self, path: Path) -> os.stat_result | None: ...  # None when absent


class RealFileOps:
    """The one production FileOps; thin delegation onto pathlib/os."""

    def read_text(self, path: Path) -> str:
        return path.read_text()

    def stat(self, path: Path) -> os.stat_result | None:
        if not path.exists():
            return None
        return path.stat()


CommandRunner = Callable[[list[str]], str]
"""Runs systemctl invocations; returns stdout, raises DaemonError on failure."""


def _run_systemctl(argv: list[str]) -> str:
    """Default CommandRunner: thin wrapper around subprocess.run (sanctioned site).

    Executes ``argv`` verbatim and returns stdout; raises ``DaemonError`` on a
    non-zero exit (expected for ``is-active``/``is-enabled`` probes — callers
    that query catch it), missing binary, or timeout.
    """
    try:
        completed = subprocess.run(argv, capture_output=True, text=True, check=False, timeout=30)
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"{' '.join(argv)} failed to run: {exc}"
        raise DaemonError(msg) from exc
    if completed.returncode != 0:
        snippet = _first_line(completed.stderr)
        msg = f"{' '.join(argv)} failed (rc={completed.returncode}): {snippet}"
        raise DaemonError(msg)
    return completed.stdout


def _first_line(text: str) -> str:
    stripped = text.strip().splitlines()
    return stripped[0][:200] if stripped else ""


def _read_packaged(name: str) -> str:
    candidate = resources.files("breezed").joinpath("templates").joinpath(name)
    if not candidate.is_file():
        msg = f"packaged resource missing: {name}"
        raise DaemonError(msg)
    return candidate.read_text(encoding="utf-8")


@dataclass(frozen=True, slots=True)
class DaemonStatus:
    unit_present: bool
    active: bool
    enabled: bool
    unit_version: str | None
    binary_version: str


def _render_unit() -> str:
    template = _read_packaged("breezed.service.template")
    installed_at = dt.datetime.now(dt.UTC).isoformat(timespec="seconds")
    return (
        template.replace("{version}", __version__)
        .replace("{installed_at}", installed_at)
        .replace("{exec_path}", EXEC_PATH)
    )


def _probe_flag(runner: CommandRunner, argv: list[str], ok_values: set[str]) -> bool:
    try:
        output = runner(argv)
    except DaemonError:
        return False
    return output.strip() in ok_values


_default_paths: InstallerPaths = InstallerPaths()
_default_fs: FileOps = RealFileOps()


def daemon_status(
    paths: InstallerPaths = _default_paths,
    *,
    runner: CommandRunner = _run_systemctl,
    fs: FileOps = _default_fs,
) -> DaemonStatus:
    unit_present = fs.stat(paths.unit_path) is not None
    unit_version: str | None = None
    if unit_present:
        try:
            unit_text = fs.read_text(paths.unit_path)
        except OSError:
            unit_text = ""
        match = _UNIT_STAMP_RE.search(unit_text)
        if match is not None:
            unit_version = match.group(1)
    return DaemonStatus(
        unit_present=unit_present,
        active=_probe_flag(runner, ["systemctl", "is-active", SERVICE_NAME], {"active"}),
        enabled=_probe_flag(
            runner, ["systemctl", "is-enabled", SERVICE_NAME], {"enabled", "enabled-runtime"}
        ),
        unit_version=unit_version,
        binary_version=__version__,
    )


def render_install_script(*, start: bool) -> str:
    """Return a reviewable idempotent install script; no side effects here."""
    start_block = _START_BLOCK.replace("SERVICE_NAME", SERVICE_NAME) if start else _NO_START_BLOCK
    script = (
        _INSTALL_SCRIPT_TEMPLATE.replace("__UNIT__", _render_unit())
        .replace("__ENV__", _ENV_SKELETON)
        .replace("__CONFIG__", _read_packaged("breezed.toml.example"))
        .replace("__ENV_MODE__", f"{ENV_MODE:o}")
        .replace("__START_BLOCK__", start_block)
    )
    leftover = re.search(r"__[A-Z_]+__", script)
    if leftover is not None:
        msg = f"install script render left unsubstituted placeholder {leftover.group(0)}"
        raise DaemonError(msg)
    return script


def render_uninstall_script() -> str:
    """Return a reviewable uninstall script; no side effects here."""
    return _UNINSTALL_SCRIPT_TEMPLATE.replace("SERVICE_NAME", SERVICE_NAME)


__all__ = [
    "ENV_MODE",
    "EXEC_PATH",
    "CommandRunner",
    "DaemonError",
    "DaemonStatus",
    "FileOps",
    "InstallerPaths",
    "RealFileOps",
    "SERVICE_NAME",
    "daemon_status",
    "render_install_script",
    "render_uninstall_script",
]
